### ISSUE TITLE
Dynamic neural orthogonal mapping for fault detection

### ISSUE THREAD

**Issue by Jesse-WJx** [htz-ecust/Semantic-consistent-Embedding#1]
您好，最近看了您的论文：Dynamic neural orthogonal mapping for fault detection，收获匪浅，我刚开始故障监测方面的研究，但是按照文章的链接没找到您论文的源码，请问您能提供源码以便学习吗？不胜感激！

**Comment by htz-ecust** [comment]
你好，在投稿其他论文时，有审稿人反馈通过github的respositories可以追溯到作者本人，违反了匿名性的规定，故审稿期间将其他respositories进行了私有化。现在审稿结束，其他respositories已经重新开放，按照论文链接即可访问！

**Comment by Jesse-WJx** [comment]
看到了，非常感谢您的分享！祝您科研顺利！---- Replied Message ***@***.***>Date11/01/2022 11:10 ***@***.***> ***@***.******@***.***>SubjectRe: [htz-ecust/Semantic-consistent-Embedding] Dynamic neural orthogonal mapping for fault detection (Issue #1)

你好，在投稿其他论文时，有审稿人反馈通过github的respositories可以追溯到作者本人，违反了匿名性的规定，故审稿期间将其他respositories进行了私有化。现在审稿结束，其他respositories已经重新开放，按照论文链接即可访问！



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/htz-ecust/Semantic-consistent-Embedding/issues/1#issuecomment-1297963726",

"url": "https://github.com/htz-ecust/Semantic-consistent-Embedding/issues/1#issuecomment-1297963726",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
